name = "GF Pack 2"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdb0107ecea7e99a77fdd051afa6e9b62fc288ba0d3fa9e2692a913ae7062c16"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.167"
unsup = "1.0.2"
