name = "GF Pack 2"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dd2045bc5d9eb9b16f08447903096c576785df1b0cb7d4173e69dbdbec32950"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.167"
unsup = "1.0.2"
