name = "GF Pack 2"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73bb12e76651b9a9b2a2df54a8d9629b5a127131c3931ab57ad472f6121efbed"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.167"
unsup = "1.0.2"
