name = "GF Pack 2"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbd7067d8de7315d328e6cc29f9b4a76b734523f96723a0ef40b0871200efbcc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.167"
unsup = "1.0.2"
