name = "GF Pack 2"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07e1a62f78a66601eb5e4d2dd272bec662ff60269206dafdd8bb549d70a4573f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.167"
unsup = "1.0.2"
