[flavor_groups.client_side]
name = "Client Mods"
description = "Which client side mods you'd like to use."
side = "client"
[[flavor_groups.client_side.choices]]
id = "default"
name = "Basics"
description = "Just JEI and Zoom and preformance mods."
[[flavor_groups.client_side.choices]]
id = "client_all"
name = "More Client side mods"
description = "Installs Apple Skin, EMI, and a few other QOL mods."

[flavor_groups.server_support]
name = "Server Support"
description = "Turn on support for client side mods."
side = "server"
[[flavor_groups.server_support.choices]]
id = "client_support_on"
name = "Client Support On"
description = "Adds mods which enhance the optional mods client side"
[[flavor_groups.server_support.choices]]
id = "client_support_off"
name = "Client Support Off"
description = "All optional client side mods have no server support"
[[flavor_groups.server_support.choices]]
id = "client_support_breaking"
name = "Client Support On (Breaking)"
description = "Adds mods to server side which make those mods requiered on the client.\nThis requires all clients enable client side mods"

[metafile.appleskin]
flavors = ["client_all", "client_support_breaking"]
[metafile.emi]
flavors = ["client_all", "client_support_on"]
[metafile.jade]
flavors = ["client_all", "client_support_breaking"]
[metafile.jade-addons-forge]
flavors = ["client_all", "client_support_breaking"]
