[flavor_groups.client_side]
name = "Client Mods"
description = "Which client side mods you'd like to use."
side = "client"
[[flavor_groups.client_side.choices]]
id = "default"
name = "Basics"
description = "Just JEI and Zoom and preformance mods."
[[flavor_groups.client_side.choices]]
id = "client_all"
name = "More Client side mods"
description = "Installs Apple Skin, EMI, and a few other QOL mods."

[flavor_groups.server_support]
name = "Server Support"
description = "Turn on support for client side mods."
side = "server"
choices = ["client_support_on", "client_support_off"]

[metafile.appleskin]
flavors = ["client_all", "client_support_on"]
[metafile.emi]
flavors = ["client_all", "client_support_on"]
[metafile.jade]
flavors = ["client_all", "client_support_on"]
[metafile.jade-addons-forge]
flavors = ["client_all", "client_support_on"]
